Update CIFS mount options
Adding mount options uid=iobroker,gid=iobroker 
This avoids error messages like 
Error: EPERM: operation not permitted, utime '/opt/iobroker/backups/zigbee_0/'
and also does not confuse users since the backup files now are owned by the familiar 'iobroker' and not 'root'.